name: Build and Deploy Hugo Site to gh-pages

on:
  push:
    branches: ["main"] # build when main updates
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - uses: actions/checkout@v4

      # 2. Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v0.26.0
        with:
          hugo-version: "0.147.2"

      # 3. Build Hugo site
      - name: Build Hugo
        run: hugo --minify

      # 4. Deploy to gh-pages branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
